name: Run Tests

on:
  push:
    branches: ["develop"]

concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true    

jobs:

  run-tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout app
        uses: actions/checkout@v3

      - name: Unit & UI Tests
        run: ./.github/scripts/run-tests
