name: Run Tests

on:
  pull_request:
    branches: ["master"]
    types: ["closed"]

concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true    

jobs:

  run-tests:
    runs-on: macos-latest
    if: github.event.pull_request.merged == true
    
    steps:
      - name: Checkout app
        uses: actions/checkout@v3

      - name: Unit & UI Tests
        run: ./.github/scripts/run-tests
