name: Merge Develop
env:
  BRANCH_NAME: ${{ github.head_ref }}
on:
  push:
    branches: ["develop"]

concurrency:
  group: ${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true    

jobs:

  run-tests:
    runs-on: macos-latest
    
    steps:
      - name: Checkout app
        uses: actions/checkout@v3

      - name: Unit & UI Tests
        env:
          WEATHER_KEY: ${{secrets.WEATHER_KEY}}
        run: ./.github/scripts/run-tests
